<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use AppBundle\Document\Attachement;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * AttachementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachementRepository extends DocumentRepository {

	
}
