<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use MongoDate as MongoDate;

class PassageRepository extends DocumentRepository {

    public function findAllByPeriodeAndIdentifiantTechnicien($startDate, $endDate, $identifiantTech) {
        $mongoStartDate = new MongoDate(strtotime($startDate));
        $mongoEndDate = new MongoDate(strtotime($endDate));
        $query = $this->createQueryBuilder('Passage')
                ->field('dateDebut')->gte($mongoStartDate)
                ->field('dateDebut')->lte($mongoEndDate)
                ->field('technicien')->equals($identifiantTech)
                ->getQuery();
        return $query->execute();
    }

    public function findAllByPeriode($startDate, $endDate) {
        $mongoStartDate = new MongoDate(strtotime($startDate));
        $mongoEndDate = new MongoDate(strtotime($endDate));
        $query = $this->createQueryBuilder('Passage')
                ->field('dateDebut')->gte($mongoStartDate)
                ->field('dateDebut')->lte($mongoEndDate)
    			->sort('technicien', 'desc')
    			->sort('dateDebut', 'asc')
                ->getQuery();
        return $query->execute();
    }

    public function findOneByIdentifiantPassage($identifiantPassage) {

        return $this->findOneBy(
                        array('id' => 'PASSAGE-' . $identifiantPassage));
    }

    public function findOneByIdentifiantEtablissementAndIdentifiantPassage($identifiantEtb, $identifiantPassage) {

        return $this->findOneBy(
                        array('id' => 'PASSAGE-' . $identifiantEtb . '-' . $identifiantPassage));
    }

    public function findByEtablissementAndCreateAt($etablissementIdentifiant, $createAt) {
        return $this->findBy(
                        array('etablissementIdentifiant' => $etablissementIdentifiant, 'createAt' => $createAt));
    }

    public function findPassagesForEtablissementsAndDay($etablissementIdentifiant, $date) {

        $passagesByEtablissementAndCreationDate = $this->findByEtablissementAndCreateAt($etablissementIdentifiant, $date);

        $allPassagesNumeros = array();
        if (count($passagesByEtablissementAndCreationDate)) {
            foreach ($passagesByEtablissementAndCreationDate as $passageByEtablissementAndCreationDate) {
                $allPassagesNumeros[$passageByEtablissementAndCreationDate->getNumeroPassageIdentifiant()] = $passageByEtablissementAndCreationDate->getNumeroPassageIdentifiant();
            }
        }
        return $allPassagesNumeros;
    }

    public function findPassagesForEtablissement($etablissementIdentifiant) {
    	$query = $this->createQueryBuilder('Passage')
    	->field('etablissementIdentifiant')->equals($etablissementIdentifiant)
    	->sort('dateCreation', 'desc')
    	->getQuery();
    	return$query->execute();
    }
    
    public function findTechniciens() {
    	$techniciens = array();
    	$date = new \DateTime();
    	$mongoEndDate = new MongoDate(strtotime($date->format('Y-m-d')));
    	$date->modify('-2 month');
    	$mongoStartDate = new MongoDate(strtotime($date->format('Y-m-d')));
    	$query = $this->createQueryBuilder('Passage')
    	->field('dateFin')->gte($mongoStartDate)
    	->field('dateFin')->lte($mongoEndDate)
    	->group(array('technicien' => 1), array('count' => 0))
    	->reduce('function (obj, prev) { prev.count++; }')
    	->getQuery();
    	$result =  $query->execute();

    	if (count($result)) {
    		foreach ($result as $item) {
    			$techniciens[$item['technicien']] = $item['technicien'];
    		}
    	}

        ksort($techniciens);
        
    	return $techniciens;
    }

    public function findToPlan() {
        $query = $this->createQueryBuilder('Passage')
                      ->field('dateDebut')->exists(false)
                      ->sort('dateCreation', 'asc')
                      ->getQuery();

        return $query->execute();
    } 

}
