<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassageRepository extends DocumentRepository {

    public function findByEtablissementAndCreateAt($etablissementIdentifiant, $createAt) {
        return $this->findBy(
                                array('etablissementIdentifiant' => $etablissementIdentifiant, 'createAt' => $createAt));
    }

    public function findPassagesForEtablissementsAndDay($etablissementIdentifiant, $date) {
        
        $passagesByEtablissementAndCreationDate = $this->findByEtablissementAndCreateAt($etablissementIdentifiant, $date);
        
        $allPassagesNumeros = array();
        if (count($passagesByEtablissementAndCreationDate)) {
            foreach ($passagesByEtablissementAndCreationDate as $passageByEtablissementAndCreationDate) {
                $allPassagesNumeros[$passageByEtablissementAndCreationDate->getNumeroPassageIdentifiant()] = $passageByEtablissementAndCreationDate->getNumeroPassageIdentifiant();
            }
        }
        return $allPassagesNumeros;
    }

}
