<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use AppBundle\Document\Societe;

/**
 * SocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocieteRepository extends DocumentRepository
{
    public function findByTerm($term,$criteria) {
        $request = $this->createQueryBuilder()
                ->find()
                ->field($criteria)->equals(new \MongoRegex('/.*'.$term.'.*/i'))
                ->getQuery()
                ->execute();
        return $request;
    }
    
    public function findAllTags() 
    {
        $request = $this->createQueryBuilder()
                ->distinct('tags')
        		->hydrate(false)
                ->getQuery()
                ->execute();
        return $request->toArray();
    }
    
    public function findAllPassages($societe) {
        $societe = $this->findOneById($societe->getId());
        $passagesArray = array();
        foreach ($societe->getEtablissements() as $etb) {
            $passages = $this->dm->getRepository('AppBundle:Passage')->findByEtablissement($etb->getId());
            foreach ($passages as $passage) {
                $passagesArray[$passage->getId()] = $passage;
            }
        }
        return $passagesArray;
    }
}
